#!/bin/sh

PREVIEW_TEXT="@real fox.quick(h){ *is_brown && it_jumps_over(dogs.lazy) }\n"\
"0123456789 ABC.DEF.GHI.JKL.MNO.PQRS.TUV.WXYZ ß <= ¶^\$#\% >="\

convert -size "1400x200" xc:"#ffffff" \
        -gravity center \
        -pointsize 38 \
        -font "$1" \
        -fill "#000000" \
        -annotate +0+0 "$PREVIEW_TEXT" \
        -flatten "$2"
